name: calculator_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  math_expressions: ^2.7.0
  mocktail: ^1.0.4
  provider: ^6.1.4

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15

flutter:
  uses-material-design: true
